# Generated by Django 3.0.5 on 2020-08-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name_plural': 'Logo'},
        ),
    ]
