# Generated by Django 3.0.5 on 2020-04-13 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATname', models.CharField(max_length=50, verbose_name='Name:')),
                ('CATdesc', models.TextField()),
                ('CATimg', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('CATslug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL:')),
                ('CATparent', models.ForeignKey(blank=True, limit_choices_to={'CATparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Main Category:')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDname', models.CharField(max_length=100, verbose_name='Name:')),
                ('PRDdesc', models.TextField(verbose_name='Description')),
                ('PRDimage', models.ImageField(blank=True, null=True, upload_to='productimg/', verbose_name='Image:')),
                ('PRDprice', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Price:')),
                ('PRDdiscount', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='After Discount:')),
                ('PRDcost', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Cost:')),
                ('PRDcreated', models.DateTimeField(verbose_name='Created at:')),
                ('PRDslug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL:')),
                ('PRDisNew', models.BooleanField(default=True, verbose_name='NEW:')),
                ('stock_quantity', models.IntegerField(default=1)),
                ('order_quantity', models.IntegerField(default=1)),
                ('PRDbrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Brand', verbose_name='Brand')),
                ('PRDcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDImage', models.ImageField(blank=True, null=True, upload_to='productimg/', verbose_name='Image:')),
                ('IMGproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product:')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Alternatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALalternatives', models.ManyToManyField(related_name='alternative_products', to='product.Product', verbose_name='Alternative Product:')),
                ('PALproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.Product', verbose_name='Product:')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Product Alternatives',
            },
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCaccessories', models.ManyToManyField(related_name='accessories_products', to='product.Product', verbose_name='Accessories Products:')),
                ('PACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.Product', verbose_name='Main Accessory:')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_date', models.DateTimeField(auto_now_add=True, verbose_name='Listed Date')),
                ('ordered_date', models.DateTimeField(verbose_name='Ordered Date')),
                ('ordered', models.BooleanField(default=False, verbose_name='Order State')),
                ('items', models.ManyToManyField(to='product.OrderItem', verbose_name='Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
