# Generated by Django 3.0.5 on 2020-06-16 22:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDdesc',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDdetails',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
