# Generated by Django 3.0.5 on 2020-06-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200617_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDtags',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Tags'),
        ),
    ]
