# Generated by Django 3.0.5 on 2020-06-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_prdtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRD_SEO_desc',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDtags',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO Tags'),
        ),
    ]
