# Generated by Django 3.0.5 on 2020-04-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200413_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDisTrend',
            field=models.BooleanField(default=False, verbose_name='Trending:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=1, verbose_name='In Stock:'),
        ),
    ]
