# Generated by Django 3.0.5 on 2020-06-25 01:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200625_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDdesc',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
