# Generated by Django 3.0.5 on 2020-04-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200416_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SDRtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Title:')),
                ('SDRimg', models.ImageField(upload_to='MainSlider/', verbose_name='Slide:')),
            ],
        ),
    ]
