# Generated by Django 3.0.5 on 2020-04-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_mainslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainslider',
            name='SDRtitle',
        ),
    ]
