# Generated by Django 3.0.5 on 2020-06-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200625_1844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvariation',
            unique_together={('variation', 'value')},
        ),
    ]
