# Generated by Django 3.0.5 on 2020-06-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200625_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_var',
            field=models.ManyToManyField(to='product.ItemVariation'),
        ),
    ]
