# Generated by Django 3.0.5 on 2020-04-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_mainslider_sdrtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Main Slider'},
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='IMGproduct',
            new_name='PRD',
        ),
    ]
