# Generated by Django 3.0.5 on 2020-04-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdisbest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDisBest',
        ),
    ]
