# Generated by Django 3.0.5 on 2020-04-17 01:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_prdisbest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDdetails',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDshipping_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Shipping Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDshipping_regions',
            field=django_countries.fields.CountryField(default='Egypt', max_length=2, verbose_name='Shipping Regions'),
        ),
    ]
