# Generated by Django 3.0.5 on 2020-08-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
