# Generated by Django 3.0.5 on 2020-04-17 01:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200417_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDshipping_regions',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Shipping Regions'),
        ),
    ]
