# Generated by Django 3.0.5 on 2020-05-02 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_address_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='giza', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.CharField(max_length=100, verbose_name='Apartment or Suite'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(max_length=50, verbose_name='Zip Code'),
        ),
    ]
