# Generated by Django 3.0.5 on 2020-08-30 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200830_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 12, 52, 5, 601761, tzinfo=utc), verbose_name='Created at:'),
        ),
    ]
