# Generated by Django 3.0.5 on 2020-05-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200502_0357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
