# Generated by Django 3.0.5 on 2020-08-30 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200830_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDcreated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at:'),
        ),
    ]
