# Generated by Django 3.0.5 on 2020-05-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200511_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
