# Generated by Django 3.0.5 on 2020-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200511_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
