# Generated by Django 3.0.5 on 2020-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200511_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
