# Generated by Django 3.0.5 on 2020-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200512_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, editable=False, verbose_name='Order State'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ordered Date'),
        ),
    ]
