# Generated by Django 3.0.5 on 2020-05-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200513_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, editable=False, verbose_name='Paid'),
        ),
    ]
