# Generated by Django 3.0.5 on 2020-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200513_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTotal',
            field=models.FloatField(default=0, editable=False, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Order item State'),
        ),
    ]
