# Generated by Django 3.0.5 on 2020-05-16 07:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20200513_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDshipping_regions',
            field=django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name='Shipping Regions'),
        ),
    ]
