# Generated by Django 3.0.5 on 2020-05-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20200516_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_ref',
        ),
    ]
