# Generated by Django 3.0.5 on 2020-05-17 09:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDdesc',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
