# Generated by Django 3.0.5 on 2020-05-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20200517_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='processing',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
