# Generated by Django 3.0.5 on 2020-05-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20200519_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PRDcat', to='product.Category', verbose_name='Category'),
        ),
    ]
