# Generated by Django 3.0.5 on 2020-05-23 09:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_order_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, editable=False, verbose_name='Ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDdetails',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
