# Generated by Django 3.0.5 on 2020-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20200604_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
