# Generated by Django 3.0.5 on 2020-06-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Cash'), ('F', 'Fawry'), ('W', 'e-Wallet')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
