# Generated by Django 3.0.5 on 2020-06-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200604_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
