# Generated by Django 3.0.5 on 2020-04-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200415_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Tel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
