# Generated by Django 3.0.5 on 2020-05-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20200513_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
