# Generated by Django 3.0.5 on 2020-06-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(blank=True, to='clients.Address', verbose_name='Address'),
        ),
    ]
